export const seoPages = {
  '/ipl-auction-simulator': {
    path: '/ipl-auction-simulator',
    title: 'IPL Auction Simulator - Free Online IPL Bidding Game',
    description: 'Use the free IPL Auction Simulator to create mock auctions, bid with friends, manage purse strategy, and build your dream fantasy IPL squad online.',
    kicker: 'IPL Auction Simulator',
    h1: 'IPL Auction Simulator',
    intro: 'Create a live IPL auction room, invite friends, bid on players, and test your fantasy cricket strategy in a fast online simulator.',
    whyTitle: 'A simulator built for real auction decisions',
    body: [
      'The IPL Auction Simulator gives every manager the same pressure as an auction table: limited purse, role gaps, fast bids, and rivals chasing the same players.',
      'Use it for IPL mega auction practice, fantasy league preparation, or a casual auction game with friends before match day.',
    ],
    features: [
      { title: 'Live Bidding', body: 'Bid in real time with private room codes and multiplayer auction rooms.' },
      { title: 'Purse Strategy', body: 'Track every buy and protect enough budget for finishers, bowlers, and backups.' },
      { title: 'Squad Results', body: 'Review final teams, player strength, and squad balance after the auction.' },
    ],
  },
  '/play-ipl-auction-online': {
    path: '/play-ipl-auction-online',
    canonicalPath: '/ipl-auction-simulator',
    index: false,
    title: 'Play IPL Auction Online - Free Multiplayer Auction Room',
    description: 'Play IPL auction online with friends. Create a room, share a code, bid live, and build a fantasy IPL team from your browser.',
    kicker: 'Play IPL Auction Online',
    h1: 'Play IPL Auction Online',
    intro: 'Start an online IPL auction in seconds with multiplayer rooms, real-time bidding, and IPL-style team building.',
    whyTitle: 'No spreadsheet, timer, or manual auction board needed',
    body: [
      'Every auction room handles bids, sold players, squads, and budget tracking so your group can focus on strategy.',
      'It works as a quick IPL auction game for friends and as a practice tool for serious fantasy cricket auction prep.',
    ],
    features: [
      { title: 'Private Rooms', body: 'Share a room code and keep your IPL auction limited to your group.' },
      { title: 'Public Rooms', body: 'Find live auction rooms when you want to play immediately.' },
      { title: 'Mobile Friendly', body: 'Join and bid from desktop or mobile browsers.' },
    ],
  },
  '/ipl-auction-with-friends': {
    path: '/ipl-auction-with-friends',
    canonicalPath: '/ipl-auction-simulator',
    index: false,
    title: 'IPL Auction With Friends - Create Private Mock Auction Rooms',
    description: 'Host an IPL auction with friends using private rooms, real-time bidding, room codes, purse tracking, and fantasy squad results.',
    kicker: 'IPL Auction With Friends',
    h1: 'Host an IPL Auction With Friends',
    intro: 'Create a private auction room, invite your group, and run a complete mock IPL auction online.',
    whyTitle: 'A better way to run friend-group fantasy auctions',
    body: [
      'Private rooms make it easy to keep your group together while everyone competes for the same player pool.',
      'The auction room tracks budgets and squads automatically, reducing confusion and keeping the game moving.',
    ],
    features: [
      { title: 'Room Codes', body: 'Invite friends with a simple code and start when everyone is ready.' },
      { title: 'Franchise Picks', body: 'Let each player manage an IPL-style team through the full auction.' },
      { title: 'Final Rankings', body: 'Compare squads once the auction ends.' },
    ],
  },
  '/mock-ipl-auction': {
    path: '/mock-ipl-auction',
    canonicalPath: '/ipl-auction-simulator',
    index: false,
    title: 'Mock IPL Auction - Practice IPL Bidding and Team Building',
    description: 'Run a mock IPL auction online to practice bidding strategy, purse management, role balance, and fantasy IPL team building.',
    kicker: 'Mock IPL Auction',
    h1: 'Mock IPL Auction',
    intro: 'Practice the IPL auction before your fantasy league or friendly tournament with a realistic online bidding simulator.',
    whyTitle: 'Practice auction plans before the real draft',
    body: [
      'Mock auctions help you understand player value, avoid overspending early, and prepare backup plans for every squad role.',
      'Use the simulator to rehearse a full mega auction or a smaller mini auction format with your group.',
    ],
    features: [
      { title: 'Bidding Practice', body: 'Test aggressive and conservative auction strategies.' },
      { title: 'Role Balance', body: 'Plan batters, wicketkeepers, all-rounders, and bowlers before the final squad.' },
      { title: 'Auction Learning', body: 'Understand how purse pressure changes player decisions.' },
    ],
  },
  '/ipl-mega-auction': {
    path: '/ipl-mega-auction',
    canonicalPath: '/ipl-auction-simulator',
    index: false,
    title: 'IPL Mega Auction Simulator - Build a Full Fantasy Squad',
    description: 'Practice an IPL mega auction online with a large player pool, franchise purse strategy, live bidding, and squad building.',
    kicker: 'IPL Mega Auction',
    h1: 'IPL Mega Auction Simulator',
    intro: 'Run a larger auction format with deeper squads, bigger decisions, and more chances to find value picks.',
    whyTitle: 'Built for long-form squad construction',
    body: [
      'Mega auctions reward patience, role planning, and backup lists. Use this page to prepare your strategy and then start a live room.',
      'Track budget across the full auction and avoid getting trapped without enough purse for late-round needs.',
    ],
    features: [
      { title: 'Large Player Pool', body: 'Use a deep player list for broad mock auction practice.' },
      { title: 'Long-Term Planning', body: 'Balance stars with depth and future-proof squad roles.' },
      { title: 'Friend Groups', body: 'Turn the mega auction into a multiplayer game night.' },
    ],
  },
  '/ipl-auction-rules': {
    path: '/ipl-auction-rules',
    canonicalPath: '/how-to-play',
    index: false,
    title: 'IPL Auction Rules - How Bidding, Purse and Squads Work',
    description: 'Learn IPL auction rules for mock auctions, including bidding flow, player base price, purse management, squad balance, and room setup.',
    kicker: 'IPL Auction Rules',
    h1: 'IPL Auction Rules',
    intro: 'Learn the auction flow before you create a room: player nominations, opening bids, purse limits, and squad construction.',
    whyTitle: 'Simple rules for a smooth auction room',
    body: [
      'Each player enters at a base price, teams bid upward, and the highest bidder wins the player when bidding stops.',
      'The key rule is purse discipline: every winning bid reduces your remaining budget, so overspending can leave gaps in the final squad.',
    ],
    features: [
      { title: 'Base Prices', body: 'Players begin from a listed starting value.' },
      { title: 'Highest Bid Wins', body: 'The last active bidder signs the player.' },
      { title: 'Purse Limit', body: 'Teams cannot buy beyond their available budget.' },
    ],
  },
  '/ipl-auction-purse-calculator': {
    path: '/ipl-auction-purse-calculator',
    canonicalPath: '/how-to-play',
    index: false,
    title: 'IPL Auction Purse Calculator - Practice Budget Strategy',
    description: 'Use IPL auction purse strategy tips to plan budgets, avoid overspending, and build better mock IPL auction squads.',
    kicker: 'IPL Auction Purse Calculator',
    h1: 'IPL Auction Purse Calculator',
    intro: 'Plan how much purse to spend on marquee players, role specialists, backups, and late value buys.',
    whyTitle: 'Budget discipline wins mock auctions',
    body: [
      'A good purse plan reserves money for every squad role instead of spending everything on the first few stars.',
      'Use the live simulator as a practical purse calculator: every bid updates your remaining budget automatically.',
    ],
    features: [
      { title: 'Track Spend', body: 'Watch remaining purse after each winning bid.' },
      { title: 'Plan Buckets', body: 'Separate marquee, core, specialist, and backup budgets.' },
      { title: 'Avoid Traps', body: 'Do not run out of budget before key roles are filled.' },
    ],
  },
  '/ipl-team-builder': {
    path: '/ipl-team-builder',
    canonicalPath: '/ipl-auction-simulator',
    index: false,
    title: 'IPL Team Builder - Build a Fantasy IPL Squad Online',
    description: 'Build a fantasy IPL team through a live auction simulator with player roles, purse strategy, squads, and final results.',
    kicker: 'IPL Team Builder',
    h1: 'IPL Team Builder',
    intro: 'Use the auction room and player directory to build a balanced fantasy IPL squad with batters, keepers, all-rounders, and bowlers.',
    whyTitle: 'Team balance matters as much as star power',
    body: [
      'The best auction squads usually combine reliable top-order players, finishing power, all-round options, and wicket-taking bowlers.',
      'Create a room to test how your team-building plan works when other managers compete for the same names.',
    ],
    features: [
      { title: 'Role Coverage', body: 'Plan every slot before the auction begins.' },
      { title: 'Franchise Squads', body: 'Browse IPL team pages for reference and inspiration.' },
      { title: 'Player Research', body: 'Use the player list to shortlist targets.' },
    ],
  },
  '/ipl-player-list': {
    path: '/ipl-player-list',
    canonicalPath: '/players',
    index: false,
    title: 'IPL Player List - Auction Player Pool, Roles and Base Prices',
    description: 'Browse the IPL player list for mock auctions, including batters, bowlers, wicketkeepers, all-rounders, teams, and base prices.',
    kicker: 'IPL Player List',
    h1: 'IPL Player List for Auction Practice',
    intro: 'Research the auction player pool before you create a mock IPL auction room or fantasy IPL team.',
    whyTitle: 'Prepare your shortlist before bidding starts',
    body: [
      'A strong auction plan starts with player research. Shortlist role options and backup targets so you can react quickly during live bidding.',
      'Use the player directory for deeper browsing and individual player pages for search-friendly profiles.',
    ],
    features: [
      { title: 'Player Roles', body: 'Find batters, bowlers, wicketkeepers, and all-rounders.' },
      { title: 'Base Prices', body: 'Check starting values before the auction.' },
      { title: 'Team Codes', body: 'See IPL team associations where available.' },
    ],
  },
};
